//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Awakener.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public int gameDBPort {
            get {
                return ((int)(this["gameDBPort"]));
            }
            set {
                this["gameDBPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2302")]
        public int rconPort {
            get {
                return ((int)(this["rconPort"]));
            }
            set {
                this["rconPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool firstTimeOpening {
            get {
                return ((bool)(this["firstTimeOpening"]));
            }
            set {
                this["firstTimeOpening"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string gameDBHost {
            get {
                return ((string)(this["gameDBHost"]));
            }
            set {
                this["gameDBHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameDBPass {
            get {
                return ((string)(this["gameDBPass"]));
            }
            set {
                this["gameDBPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameDBDatabase {
            get {
                return ((string)(this["gameDBDatabase"]));
            }
            set {
                this["gameDBDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string gameDBUser {
            get {
                return ((string)(this["gameDBUser"]));
            }
            set {
                this["gameDBUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string rconIP {
            get {
                return ((string)(this["rconIP"]));
            }
            set {
                this["rconIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string rconPass {
            get {
                return ((string)(this["rconPass"]));
            }
            set {
                this["rconPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string whitelistDBHost {
            get {
                return ((string)(this["whitelistDBHost"]));
            }
            set {
                this["whitelistDBHost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string whitelistDBPass {
            get {
                return ((string)(this["whitelistDBPass"]));
            }
            set {
                this["whitelistDBPass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string whitelistDBUser {
            get {
                return ((string)(this["whitelistDBUser"]));
            }
            set {
                this["whitelistDBUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("whitelist")]
        public string whitelistDBDatabase {
            get {
                return ((string)(this["whitelistDBDatabase"]));
            }
            set {
                this["whitelistDBDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\arma2\\cfgdayz\\arma2oaserver.rpt")]
        public string rptPath {
            get {
                return ((string)(this["rptPath"]));
            }
            set {
                this["rptPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\logs")]
        public string logDir {
            get {
                return ((string)(this["logDir"]));
            }
            set {
                this["logDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3306")]
        public int whitelistDBPort {
            get {
                return ((int)(this["whitelistDBPort"]));
            }
            set {
                this["whitelistDBPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\arma2\\arma2oaserver.exe")]
        public string exePath {
            get {
                return ((string)(this["exePath"]));
            }
            set {
                this["exePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-config=cfgdayz\\server.cfg -malloc=tbb3malloc_bi -cfg=cfgdayz\\basic.cfg -profiles" +
            "=C:\\arma2\\cfgdayz -name=cfgdayz -mod=@DayZAwaken;@hive;@Arma2NET;\"")]
        public string parameters {
            get {
                return ((string)(this["parameters"]));
            }
            set {
                this["parameters"] = value;
            }
        }
    }
}
